### ISSUE TITLE
html

### ISSUE THREAD

**Issue by michal-bootcamp** [ewelaD/java_script1#1]
- [x] usun komentarz z html
- [x] dodaj doctype w html
- [x] w konsoli przegladarki pojawia sie blad - zlikwiduj go prosze

**Comment by ewelaD** [comment]
- tak, zrobione

**Comment by michal-bootcamp** [comment]
zgodnie z rozmowa:
- [x] usun plik css i odwolanie do niego w htmlu
- [x] usunelas z html troche za duzo, bo brakuje taga `<html>`

**Comment by michal-bootcamp** [comment]
zostal jeszcze pusty plik css do usuniecia z repo
